package com.test.ecommerce.order;

import com.test.ecommerce.product.ProductRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.List;

@Service
@RequiredArgsConstructor
public class OrderItemService {

    private final OrderRepository orderRepository;
    private final ProductRepository productRepository;
    private final OrderItemRepository orderItemRepository;

    @Transactional(readOnly = true)
    public List<OrderItem> listLines(Long orderId) {
        return orderItemRepository.findAllByOrderIdFetchProduct(orderId);
    }

    /**
     * Upsert an order line. If the product already exists in the order:
     * - quantity is increased by `quantity`
     * - if `unitPrice` is not null, price is updated to that value.
     */
    @Transactional
    public OrderItem addLine(Long orderId, Long productId, int quantity, BigDecimal unitPrice) {
        if (quantity <= 0) throw new IllegalArgumentException("Quantity must be > 0");

        var order = orderRepository.findById(orderId)
                .orElseThrow(() -> new IllegalArgumentException("Order not found: " + orderId));
        var product = productRepository.findById(productId)
                .orElseThrow(() -> new IllegalArgumentException("Product not found: " + productId));

        var existing = orderItemRepository.findByOrderIdAndProductId(orderId, productId);
        if (existing.isPresent()) {
            var oi = existing.get();
            oi.setQuantity(oi.getQuantity() + quantity);
            if (unitPrice != null) oi.setUnitPrice(unitPrice);
            // lineTotal is generated by DB (or Formula), so no manual set
            touch(order); // optional: bump order updatedAt if your entity has it
            return oi;
        }

        // New line
        if (unitPrice == null) {
            throw new IllegalArgumentException("unitPrice is required for new order lines");
        }

        var oi = OrderItem.builder()
                .order(order)
                .product(product)
                .quantity(quantity)
                .unitPrice(unitPrice)
                .build();

        var saved = orderItemRepository.save(oi);
        touch(order);
        return saved;
    }

    @Transactional
    public OrderItem setQuantity(Long orderId, Long productId, int quantity) {
        if (quantity <= 0) throw new IllegalArgumentException("Quantity must be > 0");
        var oi = orderItemRepository.findByOrderIdAndProductId(orderId, productId)
                .orElseThrow(() -> new IllegalArgumentException("Order item not found"));
        oi.setQuantity(quantity);
        orderRepository.findById(orderId).ifPresent(this::touch);
        return oi;
    }

    @Transactional
    public OrderItem setUnitPrice(Long orderId, Long productId, BigDecimal unitPrice) {
        if (unitPrice == null) throw new IllegalArgumentException("unitPrice is required");
        var oi = orderItemRepository.findByOrderIdAndProductId(orderId, productId)
                .orElseThrow(() -> new IllegalArgumentException("Order item not found"));
        oi.setUnitPrice(unitPrice);
        orderRepository.findById(orderId).ifPresent(this::touch);
        return oi;
    }

    @Transactional
    public void removeLine(Long orderId, Long productId) {
        orderItemRepository.deleteByOrderIdAndProductId(orderId, productId);
        orderRepository.findById(orderId).ifPresent(this::touch);
    }

    @Transactional
    public void clear(Long orderId) {
        var lines = orderItemRepository.findAllByOrderIdFetchProduct(orderId);
        orderItemRepository.deleteAll(lines);
        orderRepository.findById(orderId).ifPresent(this::touch);
    }

    /** No-op unless your Order has an updatedAt or similar. */
    private void touch(Object orderAggregate) {
        // If your Order entity has `updatedAt`, set it here and save.
        // Example:
        // var order = (Order) orderAggregate;
        // order.setUpdatedAt(Instant.now());
        // orderRepository.save(order);
    }
}